services:
  - type: web
    name: github-webhook-flask
    runtime: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn run:app --timeout 60"
    envVars:
      - key: MONGO_URI
        value: mongodb+srv://jaypatel:jay1234@cluster0.42iqh5i.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
    plan: free
